# Generated by Django 3.1.4 on 2021-08-02 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_grocerylist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='date',
            field=models.DateField(null=True, verbose_name=datetime.date(2021, 8, 2)),
        ),
    ]
