# Generated by Django 3.1.4 on 2021-08-02 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_auto_20210802_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='date',
            field=models.DateField(null=True, verbose_name=datetime.datetime.now),
        ),
    ]
