# Generated by Django 3.1.4 on 2021-08-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0005_auto_20210802_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='item',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
