# Generated by Django 3.2.6 on 2021-08-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0006_auto_20210802_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
