# Generated by Django 3.2.6 on 2021-08-03 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0007_grocerylist_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryListArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 3, 21, 52, 1, 435416))),
            ],
        ),
    ]
