# Generated by Django 3.2.6 on 2021-08-04 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0008_grocerylistarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylistarchive',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 4, 15, 54, 29, 209736)),
        ),
    ]
