# Generated by Django 3.2.6 on 2021-08-08 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0009_alter_grocerylistarchive_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='user_id',
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='grocerylistarchive',
            name='user_id',
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grocerylistarchive',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 8, 17, 13, 2, 612069)),
        ),
    ]
