# Generated by Django 3.2.6 on 2021-08-09 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0010_auto_20210808_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='item',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grocerylistarchive',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 9, 2, 3, 53, 221749)),
        ),
    ]
