# Generated by Django 3.2.6 on 2021-08-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0011_auto_20210809_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylistarchive',
            name='item_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='grocerylistarchive',
            name='completed',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='grocerylistarchive',
            name='date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
