# Generated by Django 3.2.6 on 2021-08-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0012_auto_20210811_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerylistarchive',
            name='item_id',
        ),
    ]
