# Generated by Django 3.2.6 on 2021-08-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0013_remove_grocerylistarchive_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='item_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grocerylistarchive',
            name='item_id',
            field=models.IntegerField(null=True),
        ),
    ]
