# Generated by Django 3.2.6 on 2021-08-11 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0014_auto_20210811_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerylist',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='grocerylistarchive',
            name='item_id',
        ),
    ]
