# Generated by Django 3.2.6 on 2021-08-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0015_auto_20210811_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylistarchive',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
