# Generated by Django 3.2.6 on 2021-08-11 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0017_alter_grocerylistarchive_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime.now),
        ),
    ]
