# Generated by Django 3.2.6 on 2021-08-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0018_alter_grocerylist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylistarchive',
            name='date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
