# Generated by Django 3.2.6 on 2021-08-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0020_alter_grocerylist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocerylist',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
