# Generated by Django 3.2.6 on 2021-08-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0022_auto_20210811_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
