# Generated by Django 3.2.6 on 2021-08-13 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0023_grocerylist_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('dish', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='grocerylistarchive',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grocery.personalmenu'),
        ),
    ]
