# Generated by Django 3.2.6 on 2021-08-14 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0024_auto_20210813_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='dish',
        ),
    ]
