# Generated by Django 3.2.6 on 2021-08-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0026_dishitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishitem',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
