# Generated by Django 3.2.6 on 2021-08-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0027_dishitem_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishitem',
            name='user_id',
        ),
    ]
