# Generated by Django 3.2.6 on 2021-08-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0029_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='list_name',
            field=models.CharField(default='New List1', max_length=255),
        ),
    ]
