# Generated by Django 3.2.6 on 2021-08-17 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0030_auto_20210817_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryListName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New List1', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='list_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.grocerylistname'),
        ),
    ]
