# Generated by Django 3.2.6 on 2021-08-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0031_auto_20210817_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerylist',
            name='list_name',
        ),
        migrations.AlterField(
            model_name='grocerylistname',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
