# Generated by Django 3.2.6 on 2021-08-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0032_auto_20210817_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='list_name',
            field=models.CharField(default='New List1', max_length=255, null=True),
        ),
    ]
