# Generated by Django 3.2.6 on 2021-08-17 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0034_alter_grocerylist_list_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerylist',
            name='list_name',
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grocery.grocerylistname'),
        ),
    ]
