# Generated by Django 3.2.6 on 2021-08-17 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0035_auto_20210817_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerylist',
            name='user_id',
        ),
        migrations.AddField(
            model_name='grocerylistname',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
