# Generated by Django 3.2.6 on 2021-08-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0040_auto_20210821_1807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroceryListArchive',
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
