# Generated by Django 3.2.6 on 2021-09-10 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0042_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
