# Generated by Django 3.2.6 on 2021-09-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0047_alter_usercomments_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserComments',
        ),
    ]
