# Generated by Django 3.2.6 on 2021-09-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0051_auto_20210919_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalmenu',
            name='instruction',
            field=models.TextField(null=True),
        ),
    ]
