# Generated by Django 3.2.6 on 2021-10-04 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grocery', '0054_auto_20210922_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocerylistname',
            name='username',
        ),
        migrations.RemoveField(
            model_name='groceryitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='grocerylist',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='grocerylist',
            name='date',
        ),
        migrations.RemoveField(
            model_name='grocerylist',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='grocerylist',
            name='item',
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='completed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='favorite',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grocery.grocerylist'),
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='grocerylist',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grocerylist',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='GroceryCategory',
        ),
        migrations.DeleteModel(
            name='GroceryListName',
        ),
    ]
